// flow-typed signature: 2ea040012d60504d1aab5a91103ab659
// flow-typed version: <<STUB>>/react-enroute_v^1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-enroute'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-enroute' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-enroute/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-enroute/build/index.js' {
  declare module.exports: $Exports<'react-enroute/build/index'>;
}
